### ISSUE TITLE
Please add About to metadata

### ISSUE THREAD

**Issue by pcav** [pka/qgpkg#1]
about metadata is missing, this metadata entry is required. Please add about to metadata.txt.
Thanks.

**Comment by pka** [comment]
AFAIK mandatory fields are checked when uploading: https://github.com/pka/qgpkg/blob/master/qgis_plugin/qgpkg/metadata.txt#L9

**Comment by pcav** [comment]
The about somehow does not appear at:

http://plugins.qgis.org/plugins/QgisGeopackage/

and I get:

about metadata is missing, this metadata entry is required. Please add about to metadata.txt.

Have you uploaded the version with it?

**Comment by pka** [comment]
It's obviously a bug of the plugin web application. I tried different formats (together with Jürgen and Richard), but couldn't find a workaround. I've added the about text manually.
