### ISSUE TITLE
when loading a geopackage without a qgis-projects table

### ISSUE THREAD

**Issue by pvgenuchten** [pka/qgpkg#10]
when loading a geopackage without a qgis-projects table (or record) you get an error: "there is no project file in the database"

Alternative would be to load the geopackage anyway and add each of the geopackage tables on a project using a default style, maybe with layer-visibility:none, so not all data is loaded at once

A convention could be to use the order of gpkq-contents as default order

**Comment by doublebyte1** [comment]
This is basically initializing a new gpkg project file, from a simple gpkg (just with data). In terms of development this is more related to writing, than reading a project file, although it is reading the layers from gpkg.

**Comment by pvgenuchten** [comment]
Goal of this issue is to improve the reader, the reader should be able to read the geopackage even if the package does not have a qgis-projects table

**Comment by pka** [comment]
This has rather low priority for me, because GeoPackages can already be loaded without plugin. Let's do the OWS context reading first.

**Comment by pvgenuchten** [comment]
ok, let's merge this task with the ows-context reader task #11
