### ISSUE TITLE
extend qgis-projects with ows_context attribute

### ISSUE THREAD

**Issue by pvgenuchten** [pka/qgpkg#11]
For those clients that are not aware of the qgis-projects-file syntax, it could be an option to use ows-context as a format to define project context (layer visibility/grouping/ordering)

So when loading a geopackage, check the qgis-projects table (maybe then also rename the table to ows-projects) for the xml field, if empty see if there is an ows-context field, if so use that to define layer-ordering/grouping in the qgis project

Within OWS-10 there is some ongoing discussion on how to reference a geopackage table from an ows-context file, see https://github.com/opengeospatial/geopackage/issues/270

**Comment by pka** [comment]
We should add a separate extension spec for ows_context information.

**Comment by pka** [comment]
Included in #14
