### ISSUE TITLE
how to reference resources from layer/metadata/project

### ISSUE THREAD

**Issue by pvgenuchten** [pka/qgpkg#12]
Should the specification define a method to reference resources inside the geopackage from within a project definition, metadata or layerstyle.

A typical use case is if a layer style uses an icon defined by a png image file. If the image file is online, a http url could be used on the SLD, but if the file resides inside the geopackage in the qgis_resources table, how can you reference it from the SLD. A way to manage this would be to reference it as #qgis_resources:{name} (where name is the name of the resource)

Other use cases are when a metadata references an image to be used as a dataset thumbnail. 

Current qgis_resources table has no unique field to be used to reference the element. If it is the "name"-field, then it would be good to define "UNIQUE" on the name field

**Comment by pka** [comment]
Will define the name as UNIQUE.
