### ISSUE TITLE
gpkg_extensions table may not exist

### ISSUE THREAD

**Issue by rouault** [pka/qgpkg#2]
https://github.com/pka/qgpkg/blob/master/qgisgpkg/qgpkg.py#L207 assumes that the gpkg_extensions table always exists, but this is an optional table per http://www.geopackage.org/spec/#_extensions Requirement 58 "A GeoPackage MAY contain a table or updateable view named gpkg_extensions"

Note that GDAL/OGR created databases will generally contain it since spatial indexes are created by default and thus require creating it (and for non spatial tables, we use the gdal_aspatial extension).

**Comment by pka** [comment]
Fixed in 9c00ad6b785
