### ISSUE TITLE
'no geopackage layer in project' when writing

### ISSUE THREAD

**Issue by pvgenuchten** [pka/qgpkg#4]
when you add some layers to a blank project and try to write geopackage, you get an error 'there is no geopackage layer in the project', what does ths mean? writing a project only works on layers in a qgis project that originate from a geopackage, i kind of expected the plugin would be able to create a geopackage from a set of arbitrary gis layers? If this is not an intended scenario, then i'd suggest to mention the intended scenario in docs (qgpkg on qgis 2.10)

**Comment by pka** [comment]
I could'nt reproduce this bug. Maybe it has been solved with #3 
Can you please retry with 0.2.0?
