### ISSUE TITLE
Finalize extension spec

### ISSUE THREAD

**Issue by pka** [pka/qgpkg#7]
The [specification](https://github.com/pka/qgpkg/blob/master/qgis_geopackage_extension.md) should be finalized with the following goals:

1. Spec for storing all needed resources used in a QGIS project
2. Proper specification for styles stored from QGIS
3. Possibility to store resources as in the [QGIS Resource Sharing Plugin](http://www.akbargumbira.com/qgis_resources_sharing/author/what-to-share.html)

Open points:
* References to inlined resources in QGIS project XML should be specified
* `qgis_layer_styles` is identical to the PostGIS and SpatiaLite tables. Should it be cleaned up (e.g. unused `f_table_schema`)? Any input from your QGIS implementation, @rouault?
* Make Processing scripts sense in a gpkg? Any opinions, @akbargumbira, @anitagraser ?
* Is more metadata needed (licenses, authoring)?

**Comment by rouault** [comment]
Note that in the current implementation, the table name for the style table is layer_styles (not prefixed by qgis_), like for PostGIS and SpatiaLite

Do you really need to advertize this as an extension in gpkg_extensions ? A read-write extension that isn't known of an implementation may cause it to decide that it is too risky to update the geopackage. The OGR GPKG driver will for example throw this warning : 

```
                CPLError(CE_Warning, CPLE_AppDefined,
                         "Database relies on the '%s' (%s) extension that should "
                         "be implemented in order to read/write it safely, but is not currently. "
                         "Some data may be missing while reading that database, and updates are strongly discouraged.",
                         pszExtName, pszDefinition);
```

There's probably a lack of scope = 'informative' in the GPKG spec itself to indicate that it is fully compatible with readers and writers not aware of the extension.

**Comment by pka** [comment]
Good point @rouault. My interpretation was, that we can't call a file officially "GeoPackage" anymore, when it has additional tables which aren't specified by a gpkg_extensions. @jyutzler?

**Comment by pvgenuchten** [comment]
Related to your "is more metadata needed" question? ... yes please ...

When writing a project to Geopackage, you could check if the gpkg_metadata table is available, if not create it and save per layer all metadata that is available in the qgis project file

When reading a project to QGIS, you could check if the gpkg_metadata table is available, if so load all relevant metadata into the qgis-project file, although I expect this may be more a responsibility of QGIS-core, for any geopackage-layer that has linked metadata, it should be notified by QGIS that this metadata is available and being able to display/synchronize it. However this will have it's own tricky things, QGIS will have to be aware of the schema used in the metadata, and related to the scheme, use different xpath's to extract the required info (title/abstract/keywords/...).

**Comment by pka** [comment]
Thanks for the input, @pvgenuchten. So metadata can already be stored according to http://www.geopackage.org/spec/#extension_metadata
It's great when we don't need our own tables for this extension. For other aspects (e.g. SLD styling) I didn't try to define generic tables, because I'm expecting that other applications (GeoServer, Arc) have additional requirements and will eventually define their own extension.

**Comment by jyutzler** [comment]
The way we have it worded now, if you have in your SQLite Database both GeoPackage core data and additional non-core tables and columns it is by definition an Extended GeoPackage. There is no downside to this. If you want other people to be able to use your non-core tables and columns, use the extension mechanism. Without looking at this too closely, what you guys are doing appears fine.

**Comment by pka** [comment]
I'm opting for an explicit extension, because the QGIS project can get invalid when the data structure changes. See 5c05166
