### ISSUE TITLE
store SLD on geopackage

### ISSUE THREAD

**Issue by pvgenuchten** [pka/qgpkg#8]
The qgis_geopackage_extension defines a table qgis_layer_styles  which seems not created by the current qgis plugin. The layer_styles table has a field styleSLD and a field styleQML. The idea is when loading a geopackage to see which of the fields is filled, and use that to render the layer? 

See also this discussion https://github.com/opengeospatial/geopackage/issues/270 which discusses similar goal from a more wider OGC perspective.

**Comment by pka** [comment]
Will look at that in the course of #7, thanks!

**Comment by pka** [comment]
I propose a separate table for that. See #11

**Comment by pka** [comment]
Included in #14
