### ISSUE TITLE
when loading a geopackage, what order to look for layer styling?

### ISSUE THREAD

**Issue by pvgenuchten** [pka/qgpkg#9]
according to the extension definition a layer style can be defined in 3 ways: 
- as part of the qgis-project definition 
- in the qgis-layer-styles:styleQML field 
- in the qgis-layer-styles:styleSLD field 

In what order should these fields be parsed to see which can be used, my suggestion:
- qgis-layer-styles:styleQML
- qgis-layer-styles:styleSLD
- qgis-project definition 
- use a default style

**Comment by pka** [comment]
When a QGIS project is present, the order is defined there. Let's do a OWS context reading implementation and define the loading logic there.

**Comment by pvgenuchten** [comment]
decided to use a separated workflow for ows-context loading and qgis-project loading, so issue is not relevant anymore
